import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Text } from '@/components/Typography';
import { useAppTheme } from '@/contexts/app-theme';

type EventDetails = { id: number; name: string; description: string; requirements?: string[]; type: string; location: string; event_start_date: string; event_end_date: string; booking_start_date: string; booking_end_date: string; status: string; capacity: number | null; remaining_capacity: number | null; can_book: boolean; is_event?: boolean; is_booked?: boolean; event_booking_id?: number | null };

function formatDateRange(startValue: string, endValue: string) {
  const start = new Date(`${startValue}T00:00:00`);
  const end = new Date(`${endValue}T00:00:00`);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return `${startValue} – ${endValue}`;
  const startMonth = start.toLocaleDateString('en-US', { month: 'long' });
  const sameYear = start.getFullYear() === end.getFullYear();
  const sameMonth = sameYear && start.getMonth() === end.getMonth();
  if (start.toDateString() === end.toDateString()) return start.toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' });
  if (sameMonth) return `${startMonth} ${start.getDate()} – ${end.getDate()}, ${start.getFullYear()}`;
  return `${start.toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' })} – ${end.toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' })}`;
}

export default function EventDetailsScreen() {
  const { colors } = useAppTheme(); const params = useLocalSearchParams<{ event?: string }>(); let event: EventDetails | null = null;
  try { event = params.event ? JSON.parse(params.event) : null; } catch { event = null; }
  if (!event) return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]}><View style={s.empty}><Text style={{ color: colors.text }}>This event/service is no longer available.</Text><Pressable onPress={() => router.back()} style={s.button}><Text style={s.buttonText}>Go Back</Text></Pressable></View></SafeAreaView>;
  const bookingStart = new Date(`${event.booking_start_date}T00:00:00`); const label = event.status === 'active' ? 'AVAILABLE NOW' : event.status.replace('_', ' ').toUpperCase();
  const unavailable = event.status === 'fully_booked' ? 'Fully Booked' : event.status === 'upcoming' ? `Booking opens ${bookingStart.toLocaleDateString()}` : event.status === 'expired' ? 'Booking has closed' : null;
  const openAction = () => event!.is_event && event!.is_booked && event!.event_booking_id ? router.push({ pathname: '/event-pass' as never, params: { bookingId: String(event!.event_booking_id) } }) : router.push({ pathname: '/booking', params: { serviceId: String(event!.id) } });
  const actionLabel = event.is_booked ? 'View QR Pass' : event.can_book ? 'Book Now' : event.status === 'fully_booked' ? 'Fully Booked' : 'Upcoming';
  const eventDate = formatDateRange(event.event_start_date, event.event_end_date);
  const bookingPeriod = formatDateRange(event.booking_start_date, event.booking_end_date);
  const buttonColors: [string, string, string] = event.can_book && !event.is_booked ? ['#003B91', '#075BCF', '#0784FF'] : !event.can_book && !event.is_booked ? ['#9AA3B2', '#9AA3B2', '#9AA3B2'] : [colors.accent, colors.accent, colors.accent];
  return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]} edges={['top']}><View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><Ionicons name="chevron-back" size={27} color="#FFF" /></Pressable><Text style={s.headerTitle}>Event Details</Text></View><ScrollView contentContainerStyle={s.content}><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={s.top}><Text style={[s.kind, { color: colors.accent }]}>{event.type}</Text><Text style={[s.status, event.status === 'active' && s.statusAvailable]}>{label}</Text></View><Text style={[s.title, { color: colors.text }]}>{event.name}</Text><Text style={[s.description, { color: colors.muted }]}>{event.description}</Text><View style={[s.infoDivider, { backgroundColor: colors.border }]} /><Info icon="calendar-outline" label="Booking Period" value={bookingPeriod} first /><Info icon="calendar-number-outline" label="Event Date" value={eventDate} /><Info icon="location-outline" label="Location" value={event.location || 'Not specified'} />{event.remaining_capacity !== null && <Info icon="people-outline" label="Availability" value={`${event.remaining_capacity} of ${event.capacity} slots remaining`} />}<View style={[s.requirements, { borderTopColor: colors.border }]}><View style={s.requirementsTitle}><Ionicons name="document-text-outline" size={18} color={colors.accent} /><Text style={[s.requirementsHeading, { color: colors.text }]}>Event Requirements</Text></View>{event.requirements?.length ? event.requirements.map((item, index) => <View key={`${index}-${item}`} style={s.requirementRow}><Text style={[s.requirementNumber, { color: colors.accent }]}>{index + 1}.</Text><Text style={[s.requirementText, { color: colors.text }]}>{item}</Text></View>) : <Text style={[s.noRequirements, { color: colors.muted }]}>No specific requirements have been listed for this event.</Text>}</View>{event.is_booked && <View style={s.booked}><Ionicons name="checkmark-circle" size={18} color="#17713C" /><Text style={s.bookedText}>Booked</Text></View>}{unavailable && !event.is_booked && <View style={s.notice}><Ionicons name="information-circle" size={19} color="#9A5600" /><Text style={s.noticeText}>{unavailable}</Text></View>}<Pressable disabled={!event.can_book && !event.is_booked} onPress={openAction} style={s.button}><LinearGradient colors={buttonColors} start={{ x: 0, y: 0.5 }} end={{ x: 1, y: 0.5 }} style={s.buttonGradient}><Text style={s.buttonText}>{actionLabel}</Text></LinearGradient></Pressable></View></ScrollView></SafeAreaView>;
}
function Info({ icon, label, value, first = false }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; first?: boolean }) { const { colors } = useAppTheme(); return <View style={[s.info, first ? s.firstInfo : { borderTopColor: colors.border }]}><View style={[s.icon, { backgroundColor: colors.iconBackground }]}><Ionicons name={icon} size={18} color={colors.accent} /></View><View style={s.infoCopy}><Text style={[s.infoLabel, { color: colors.muted }]}>{label}</Text><Text style={[s.infoValue, { color: colors.text }]}>{value}</Text></View></View>; }
const s = StyleSheet.create({ safe: { flex: 1 }, header: { alignItems: 'center', backgroundColor: '#07419C', flexDirection: 'row', minHeight: 70, paddingHorizontal: 12 }, back: { padding: 10 }, headerTitle: { color: '#FFF', fontSize: 19, fontWeight: '800', marginLeft: 5 }, content: { alignItems: 'center', padding: 18, paddingBottom: 32 }, card: { borderRadius: 18, borderWidth: 1, maxWidth: 560, padding: 18, width: '100%' }, top: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' }, kind: { flex: 1, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, status: { backgroundColor: '#FFF0D4', borderRadius: 12, color: '#925000', flexShrink: 0, fontSize: 9, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 5 }, statusAvailable: { backgroundColor: '#E4F6E9', color: '#17713C' }, title: { color: '#10336C', fontSize: 25, fontWeight: '900', lineHeight: 32, marginTop: 16 }, description: { fontSize: 13, lineHeight: 20, marginTop: 7 }, infoDivider: { height: StyleSheet.hairlineWidth, marginTop: 17, width: '100%' }, info: { alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', minHeight: 66, paddingVertical: 10 }, firstInfo: { borderTopWidth: 0 }, icon: { alignItems: 'center', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, infoCopy: { flex: 1, marginLeft: 11, minWidth: 0 }, infoLabel: { fontSize: 10 }, infoValue: { flexShrink: 1, fontSize: 13, fontWeight: '700', lineHeight: 18, marginTop: 2 }, requirements: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 16 }, requirementsTitle: { alignItems: 'center', flexDirection: 'row', gap: 8, marginBottom: 10 }, requirementsHeading: { fontSize: 14, fontWeight: '800' }, requirementRow: { alignItems: 'flex-start', flexDirection: 'row', marginBottom: 7 }, requirementNumber: { fontSize: 12, fontWeight: '800', marginRight: 7, minWidth: 18 }, requirementText: { flex: 1, fontSize: 12, lineHeight: 18 }, noRequirements: { fontSize: 12, lineHeight: 18 }, notice: { alignItems: 'center', backgroundColor: '#FFF5E6', borderRadius: 10, flexDirection: 'row', gap: 8, marginTop: 12, padding: 12 }, noticeText: { color: '#744400', flex: 1, fontSize: 11, lineHeight: 16 }, booked: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#E4F6E9', borderRadius: 12, flexDirection: 'row', gap: 5, marginTop: 12, paddingHorizontal: 10, paddingVertical: 6 }, bookedText: { color: '#17713C', fontSize: 11, fontWeight: '800' }, button: { borderRadius: 11, marginTop: 18, minHeight: 48, overflow: 'hidden', width: '100%' }, buttonGradient: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 16, width: '100%' }, buttonText: { color: '#FFF', fontSize: 14, fontWeight: '800' }, empty: { alignItems: 'center', flex: 1, justifyContent: 'center', padding: 30 } });
