import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Text } from '@/components/Typography';
import { useAppTheme } from '@/contexts/app-theme';

type EventDetails = { id: number; name: string; description: string; type: string; location: string; start_datetime: string; end_datetime: string; status: string; capacity: number | null; remaining_capacity: number | null; can_book: boolean };

export default function EventDetailsScreen() {
  const { colors } = useAppTheme();
  const params = useLocalSearchParams<{ event?: string }>();
  let event: EventDetails | null = null;
  try { event = params.event ? JSON.parse(params.event) : null; } catch { event = null; }
  if (!event) return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]}><View style={s.empty}><Text style={{ color: colors.text }}>This event/service is no longer available.</Text><Pressable onPress={() => router.back()} style={s.button}><Text style={s.buttonText}>Go Back</Text></Pressable></View></SafeAreaView>;
  const start = new Date(event.start_datetime); const end = new Date(event.end_datetime);
  const label = event.status === 'active' ? 'AVAILABLE NOW' : event.status.replace('_', ' ').toUpperCase();
  const unavailable = event.status === 'fully_booked' ? 'Fully Booked' : event.status === 'upcoming' ? `Upcoming · available ${start.toLocaleString()}` : null;
  return <SafeAreaView style={[s.safe, { backgroundColor: colors.background }]} edges={['top']}><View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><Ionicons name="chevron-back" size={27} color="#FFF" /></Pressable><Text style={s.headerTitle}>Event Details</Text></View><ScrollView contentContainerStyle={s.content}><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={s.top}><Text style={s.kind}>{event.type}</Text><Text style={s.status}>{label}</Text></View><Text style={[s.title, { color: colors.text }]}>{event.name}</Text><Text style={[s.description, { color: colors.muted }]}>{event.description}</Text><Info icon="calendar-outline" label="Date" value={`${start.toLocaleDateString()} – ${end.toLocaleDateString()}`} /><Info icon="time-outline" label="Time" value={`${start.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} – ${end.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}`} /><Info icon="location-outline" label="Location" value={event.location || 'Not specified'} />{event.remaining_capacity !== null && <Info icon="people-outline" label="Availability" value={`${event.remaining_capacity} of ${event.capacity} slots remaining`} />}{unavailable && <View style={s.notice}><Ionicons name="information-circle" size={19} color="#9A5600" /><Text style={s.noticeText}>{unavailable}</Text></View>}<Pressable disabled={!event.can_book} onPress={() => router.push({ pathname: '/booking', params: { serviceId: String(event!.id) } })} style={[s.button, !event.can_book && s.disabled]}><Text style={s.buttonText}>{event.can_book ? 'Book Now' : event.status === 'fully_booked' ? 'Fully Booked' : 'Upcoming'}</Text></Pressable></View></ScrollView></SafeAreaView>;
}

function Info({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { const { colors } = useAppTheme(); return <View style={s.info}><View style={s.icon}><Ionicons name={icon} size={20} color="#B65C00" /></View><View style={s.infoCopy}><Text style={[s.infoLabel, { color: colors.muted }]}>{label}</Text><Text style={[s.infoValue, { color: colors.text }]}>{value}</Text></View></View>; }

const s = StyleSheet.create({ safe: { flex: 1 }, header: { alignItems: 'center', backgroundColor: '#07419C', flexDirection: 'row', minHeight: 70, paddingHorizontal: 12 }, back: { padding: 10 }, headerTitle: { color: '#FFF', fontSize: 19, fontWeight: '800', marginLeft: 5 }, content: { padding: 18 }, card: { borderRadius: 18, borderWidth: 1, padding: 18 }, top: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, kind: { color: '#9A5600', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, status: { backgroundColor: '#FFF0D4', borderRadius: 12, color: '#925000', fontSize: 9, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 5 }, title: { fontSize: 24, fontWeight: '800', lineHeight: 31, marginTop: 18 }, description: { fontSize: 13, lineHeight: 20, marginBottom: 16, marginTop: 7 }, info: { alignItems: 'center', borderTopColor: '#E9EEF5', borderTopWidth: 1, flexDirection: 'row', paddingVertical: 13 }, icon: { alignItems: 'center', backgroundColor: '#FFF5E6', borderRadius: 20, height: 40, justifyContent: 'center', width: 40 }, infoCopy: { flex: 1, marginLeft: 11 }, infoLabel: { fontSize: 10 }, infoValue: { fontSize: 13, fontWeight: '600', marginTop: 2 }, notice: { alignItems: 'center', backgroundColor: '#FFF5E6', borderRadius: 10, flexDirection: 'row', gap: 8, marginTop: 12, padding: 12 }, noticeText: { color: '#744400', flex: 1, fontSize: 11, lineHeight: 16 }, button: { alignItems: 'center', backgroundColor: '#B65C00', borderRadius: 10, marginTop: 18, paddingVertical: 14 }, disabled: { backgroundColor: '#9AA3B2' }, buttonText: { color: '#FFF', fontSize: 14, fontWeight: '800' }, empty: { alignItems: 'center', flex: 1, justifyContent: 'center', padding: 30 } });
