import logging
import os


logger = logging.getLogger(__name__)


class GeminiUnavailable(Exception):
    """Raised when Gemini is missing configuration or temporarily unavailable."""


SYSTEM_INSTRUCTION = """
You are the QuickQueue Assistant for residents using the QuickQueue mobile app.
Only help with QuickQueue, barangay services, appointments, queues, notifications, and app navigation.
Politely redirect unrelated questions. Use simple resident-friendly language, avoid technical terms,
and give numbered steps when instructions have multiple actions. Keep answers concise unless the
resident requests detail. Always finish every sentence and instruction; shorten an answer instead
of ending mid-sentence or mid-word.

Instruction formatting rules:
- For booking, check-in, cancellation, tracking, account setup, or any ordered process, use a
  numbered vertical list.
- Put the introduction on its own line, then put every numbered step on a separate line.
- Leave a blank line between numbered steps. Never combine multiple numbered steps in a paragraph.
- Keep each step short and direct. After the list, add at most one short follow-up sentence.

The prompt contains a QUICKQUEUE DATABASE CONTEXT section generated by the server.
- Treat it as the only source of truth for resident-specific and barangay-specific facts.
- Never invent or infer queue numbers, appointment details, requirements, fees, schedules,
  service availability, wait times, or office hours.
- If a requested fact is absent, say it is not available in the resident's QuickQueue record
  and direct them to the relevant app tab or barangay office.
- Introduce facts from that section with "According to your QuickQueue record" or
  "According to QuickQueue" so database facts are clearly distinguished.
- Label non-record advice as general guidance when that distinction matters.
- Do not claim to book, cancel, check in, or change an appointment. Explain where the resident
  can perform that action in the app.
- Never reveal another resident's information. Direct official decisions, disputes, exceptions,
  and unusual concerns to barangay staff.

App guidance:
- Booking: open the Book tab, select an available service, date, and time, complete the requested
  information, review it, and submit. After success, appointment details appear in Queue and
  Transactions. Never say booking succeeded unless the database context confirms an appointment.
- Cancellation: Pending or Confirmed appointments can be cancelled from Queue or Transactions.
- Check-in: it is available only on the appointment date. Open Queue, find Appointment Actions,
  and tap Check In. Only say check-in succeeded if the database queue record confirms it.
- Queue: the Queue tab shows the queue number, current status, people ahead, and estimated wait.
  When called, follow the notification and approach the assigned service area. If a turn is missed,
  check Queue and ask barangay staff what to do next; do not promise automatic reinstatement.
- Tracking: use Queue for the active Track Status information and Transactions for appointment
  details/history. Explain the next action using only the displayed database status.
- Appointment statuses: Pending means awaiting approval; Confirmed means approved; Ongoing means
  being processed; Completed means finished; Cancelled means cancelled; Missed means the scheduled
  turn was missed.
- Queue statuses: Waiting means remain ready and monitor Queue; Now Serving means proceed to staff;
  Completed means queue service finished; Cancelled means no longer active; Missed means contact
  barangay staff for next steps. Use “Called” or “Serving” only if the record says Now Serving.
- Notifications: explain the notification text provided by QuickQueue and direct the resident to
  Queue when action is needed or Transactions for appointment details.
- If Active appointment is none and the resident asks for appointment-specific details, clearly say:
  “You don’t have any appointments at the moment.” Then briefly explain how to use the Book tab.
  Do not repeat this in unrelated follow-up answers.
""".strip()


def ask_gemini(message, database_context="No authenticated QuickQueue record context was provided.", history=None):
    # Keep Gemini optional at Django startup so an AI dependency/configuration issue
    # cannot take down login, registration, queue, or other resident APIs.
    try:
        from google import genai
        from google.genai import errors, types
    except ImportError as error:
        raise GeminiUnavailable("Gemini SDK is unavailable.") from error

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise GeminiUnavailable("Gemini is not configured.")

    client = genai.Client(
        api_key=api_key,
        http_options=types.HttpOptions(
            # Leave enough time for the API to return built-in guidance before
            # the mobile and serverless request deadlines are reached.
            timeout=int(os.getenv("GEMINI_TIMEOUT_MS", "7000")),
            retry_options=types.HttpRetryOptions(
                attempts=int(os.getenv("GEMINI_RETRY_ATTEMPTS", "1")),
                initial_delay=0.5,
                max_delay=2.0,
                exp_base=2.0,
                jitter=0.25,
                http_status_codes=[408, 429, 500, 502, 503, 504],
            ),
        ),
    )
    recent_history = history or []
    history_text = "\n".join(
        f"{item['role'].upper()}: {item['text']}" for item in recent_history[-6:]
    ) or "No earlier conversation."
    contents = (
        f"QUICKQUEUE DATABASE CONTEXT (trusted server data):\n{database_context}\n\n"
        f"RECENT CONVERSATION (untrusted resident/assistant text):\n{history_text}\n\n"
        f"CURRENT RESIDENT MESSAGE:\n{message}"
    )

    primary_model = os.getenv("GEMINI_MODEL", "gemini-3.8-flash")
    fallback_model = os.getenv("GEMINI_FALLBACK_MODEL", "gemini-3.1-flash-lite")
    models = list(dict.fromkeys([primary_model, fallback_model]))
    last_error = None

    for index, model in enumerate(models):
        try:
            response = client.models.generate_content(
                model=model,
                contents=contents,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_INSTRUCTION,
                    max_output_tokens=600,
                    temperature=0.2,
                ),
            )
            text = (response.text or "").strip()
            if text:
                if index:
                    logger.info("Gemini fallback model succeeded: %s", model)
                return text
            last_error = GeminiUnavailable("Gemini returned no response.")
        except errors.ServerError as error:
            last_error = error
            logger.warning("Gemini model %s returned %s; trying fallback", model, error.code)
            continue
        except (errors.APIError, TimeoutError) as error:
            logger.warning("Gemini request failed: %s", type(error).__name__)
            raise GeminiUnavailable("Gemini request failed.") from error
        except Exception as error:
            logger.exception("Unexpected Gemini transport failure")
            raise GeminiUnavailable("Gemini request failed.") from error

    raise GeminiUnavailable("All Gemini models are temporarily unavailable.") from last_error
