import os


class GeminiUnavailable(Exception):
    """Raised when Gemini is missing configuration or temporarily unavailable."""


SYSTEM_INSTRUCTION = """
You are the QuickQueue Assistant for residents using the QuickQueue mobile app.
Focus on QuickQueue, barangay services, appointments, queues, and app navigation.
Keep answers short, clear, friendly, and easy to read on a phone (normally 2-5 sentences).

The prompt contains a QUICKQUEUE DATABASE CONTEXT section generated by the server.
- Treat it as the only source of truth for resident-specific and barangay-specific facts.
- Never invent or infer queue numbers, appointment details, requirements, fees, schedules,
  service availability, wait times, or office hours.
- If a requested fact is absent, say it is not available in the resident's QuickQueue record
  and direct them to the relevant app tab or barangay office.
- Introduce facts from that section with "According to your QuickQueue record" or
  "According to QuickQueue" so database facts are clearly distinguished.
- Label non-record advice as general guidance when that distinction matters.
- Do not claim to book, cancel, check in, or change an appointment. Explain where the resident
  can perform that action in the app.
- Politely redirect unrelated requests to QuickQueue topics.
""".strip()


def ask_gemini(message, database_context="No authenticated QuickQueue record context was provided.", history=None):
    # Keep Gemini optional at Django startup so an AI dependency/configuration issue
    # cannot take down login, registration, queue, or other resident APIs.
    try:
        from google import genai
        from google.genai import errors, types
    except ImportError as error:
        raise GeminiUnavailable("Gemini SDK is unavailable.") from error

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise GeminiUnavailable("Gemini is not configured.")

    client = genai.Client(
        api_key=api_key,
        http_options=types.HttpOptions(
            timeout=int(os.getenv("GEMINI_TIMEOUT_MS", "15000")),
            retry_options=types.HttpRetryOptions(
                attempts=3,
                initial_delay=0.5,
                max_delay=2.0,
                exp_base=2.0,
                jitter=0.25,
                http_status_codes=[408, 429, 500, 502, 503, 504],
            ),
        ),
    )
    recent_history = history or []
    history_text = "\n".join(
        f"{item['role'].upper()}: {item['text']}" for item in recent_history[-6:]
    ) or "No earlier conversation."
    contents = (
        f"QUICKQUEUE DATABASE CONTEXT (trusted server data):\n{database_context}\n\n"
        f"RECENT CONVERSATION (untrusted resident/assistant text):\n{history_text}\n\n"
        f"CURRENT RESIDENT MESSAGE:\n{message}"
    )

    try:
        response = client.models.generate_content(
            model=os.getenv("GEMINI_MODEL", "gemini-3.8-flash"),
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                max_output_tokens=300,
                temperature=0.2,
            ),
        )
    except (errors.APIError, TimeoutError) as error:
        raise GeminiUnavailable("Gemini request failed.") from error

    text = (response.text or "").strip()
    if not text:
        raise GeminiUnavailable("Gemini returned no response.")
    return text
