# Generated by Django 5.2.7 on 2026-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
