# Generated by Django 5.2.7 on 2026-07-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0003_alter_barangay_contact_number_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, help_text='Requirements needed for this service.')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated processing time in minutes.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
