# Generated by Django 5.2.7 on 2026-07-09 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('max_daily_appointments', models.PositiveIntegerField(default=50, help_text='Maximum appointments allowed per day.')),
                ('estimated_duration', models.PositiveIntegerField(default=15, help_text='Estimated processing time in minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_services', to='qq.barangay')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_services', to='qq.service')),
            ],
            options={
                'unique_together': {('barangay', 'service')},
            },
        ),
    ]
