# Generated by Django 5.2.7 on 2026-07-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0006_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
