# Generated by Django 5.2.7 on 2026-07-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0008_resident_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(blank=True)),
                ('appointment_date', models.DateField()),
                ('queue_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('O', 'Ongoing'), ('D', 'Completed'), ('X', 'Cancelled'), ('M', 'Missed')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='qq.barangayservice')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='qq.resident')),
            ],
            options={
                'ordering': ['appointment_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('AC', 'Appointment Confirmed'), ('AR', 'Appointment Reminder'), ('QU', 'Queue Update'), ('CA', 'Appointment Cancelled'), ('CO', 'Appointment Completed')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='qq.appointment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='qq.resident')),
            ],
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('S', 'Now Serving'), ('C', 'Completed'), ('M', 'Missed'), ('X', 'Cancelled')], default='W', max_length=1)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_ticket', to='qq.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_appointments', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='qq.barangayservice')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='qq.timeslot'),
        ),
    ]
