# Generated by Django 5.2.7 on 2026-07-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0009_appointment_notification_queueticket_timeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='barangay_service',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='qq.barangay'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_appointments',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('barangay', 'start_time', 'end_time'), name='unique_barangay_timeslot'),
        ),
    ]
