# Generated by Django 5.2.7 on 2026-07-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0010_remove_timeslot_barangay_service_timeslot_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='qq.barangay'),
        ),
    ]
