# Generated by Django 6.0.6 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qq", "0012_alter_resident_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="municipality",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="resident",
            name="province",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="resident",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
