# Generated by Django 6.0.6 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qq", "0013_resident_municipality_resident_province_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="municipality",
            field=models.CharField(default="Toledo City", max_length=100),
        ),
        migrations.AlterField(
            model_name="resident",
            name="province",
            field=models.CharField(default="Cebu", max_length=100),
        ),
    ]
