# Generated by Django 5.2.7 on 2026-09-20 12:59

import django.db.models.deletion
import qq.models.document_template
import qq.models.generated_document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0027_alter_queueticket_queue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_file', models.FileField(upload_to=qq.models.document_template.template_upload_path)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='qq.barangay')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_templates', to='qq.service')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('service__name',),
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to=qq.models.generated_document.generated_upload_path)),
                ('status', models.CharField(choices=[('G', 'Generated'), ('A', 'Archived')], default='G', max_length=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='qq.documenttemplate')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_document', to='qq.queueticket')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('barangay', 'service'), name='unique_template_per_barangay_service'),
        ),
    ]
