# Generated by Django 5.2.7 on 2026-10-06 03:30

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def copy_special_service_dates(apps, schema_editor):
    Service = apps.get_model('qq', 'Service')
    for service in Service.objects.filter(is_temporary=True).iterator():
        start_date = timezone.localtime(service.start_datetime).date() if service.start_datetime else None
        end_date = timezone.localtime(service.end_datetime).date() if service.end_datetime else None
        service.event_start_date = start_date
        service.event_end_date = end_date
        service.booking_start_date = start_date
        service.booking_end_date = end_date
        if not service.capacity:
            slot_capacity = sum(slot.max_appointments for slot in service.available_time_slots.all())
            booking_count = service.appointments.exclude(status__in=['X', 'M']).count()
            service.capacity = max(slot_capacity, booking_count, 1)
        service.save(update_fields=[
            'event_start_date', 'event_end_date', 'booking_start_date', 'booking_end_date', 'capacity',
        ])


def restore_special_service_datetimes(apps, schema_editor):
    Service = apps.get_model('qq', 'Service')
    current_timezone = timezone.get_current_timezone()
    for service in Service.objects.filter(is_temporary=True).iterator():
        service.start_datetime = timezone.make_aware(
            datetime.datetime.combine(service.event_start_date, datetime.time.min),
            current_timezone,
        ) if service.event_start_date else None
        service.end_datetime = timezone.make_aware(
            datetime.datetime.combine(service.event_end_date, datetime.time.max),
            current_timezone,
        ) if service.event_end_date else None
        service.save(update_fields=['start_datetime', 'end_datetime'])


class Migration(migrations.Migration):

    dependencies = [
        ('qq', '0032_eventbooking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_queue_per_day',
        ),
        migrations.AddField(
            model_name='service',
            name='booking_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_special_service_dates, restore_special_service_datetimes),
        migrations.RemoveField(
            model_name='service',
            name='available_time_slots',
        ),
        migrations.RemoveField(
            model_name='service',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_datetime',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='qq.timeslot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('time_slot__isnull', False)), fields=('appointment_date', 'barangay', 'service', 'queue_number'), name='unique_queue_per_day'),
        ),
    ]
